name: rocky build workflows

on:
  push:
    branches: 
      - main
  
permissions:
  contents: read
  
jobs:
  build:
    runs-on: ${{ matrix.runner }}
    container:
      image: quay.io/centos/centos:${{ matrix.stream }}
      options: --platform ${{ matrix.platform }}
    strategy:
      matrix:
        include:
          - arch: amd64
            runner: ubuntu-24.04
            platform: linux/amd64
            artifact: x86-64
            version: 9
            stream: stream9
          - arch: amd64
            runner: ubuntu-24.04
            platform: linux/amd64
            artifact: x86-64
            version: 10
            stream: stream10
          - arch: arm64
            runner: ubuntu-24.04-arm
            platform: linux/arm64
            artifact: Arm64
            version: 9
            stream: stream9
          - arch: arm64
            runner: ubuntu-24.04-arm
            platform: linux/arm64
            artifact: Arm64
            version: 10
            stream: stream10

    steps:
      - name: Checkout main repository code
        uses: actions/checkout@v4

      - name: Set TERM variable
        run: echo "TERM=xterm" >> $GITHUB_ENV
                  
      - name: install system package
        run: |
            dnf update -y
            dnf install gcc g++ make git jq unzip wget -y

      - name: install xengine library
        run: |
            cd XEngine_Source
            chmod 777 *
            ./XEngine_LINEnv.sh -i 3
            
      - name: install depend library
        run: |
          dnf search srtp
          dnf search srt
          dnf install libsrtp-devel srt-devel -y
